export const CREATURE_IDENTIFICATION_TRAITS: string[] = [
    "aberration",
    "animal",
    "beast",
    "celestial",
    "construct",
    "dragon",
    "elemental",
    "fey",
    "fiend",
    "fungus",
    "humanoid",
    "monitor",
    "ooze",
    "plant",
    "shade",
    "spirit",
    "swarm",
    "troop",
    "undead",
    "trap",
];

export const ADJECTIVE_CREATURE_TRAITS: string[] = [
    "alchemical",
    "amphibious",
    "aquatic",
    "clockwork",
    "ethereal",
    "incorporeal",
    "summoned",
    "holy",
    "unholy",
    "acid",
    "cold",
    "electricity",
    "fire",
    "force",
    "sonic",
    "vitality",
    "void",
    "air",
    "earth",
    "metal",
    "water",
    "wood",
    "complex",
    "mechanical",
    "environmental",
    "magical",
];

export const ELITE_WEAK: string[] = ["elite", "weak"];
